version: '3.8'

services:
  color-server:
    build: .
    container_name: color-server
    ports:
      - "3000:3000"
    environment:
      - COLOR=skyblue
      - PORT=3000
    volumes:
      - ./public:/app/public:ro
    restart: unless-stopped
