# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: color-server
spec:
  containers:
    - name: color-server
      image: archimonde13/color-server:1.0.3
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: color-server-secret
