# pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: color-server
spec:
  containers:
    - name: color-server
      image: kubernetes-test-color-server
      ports:
        - containerPort: 3000
      envFrom:
        - secretRef:
            name: color-server-secret
