image:
  repository: archimonde13/color-server
  tag: latest

service:
  type: NodePort
  ports:
    colorServer: 3000
  nodePort: 30001
resources:
  limits:
    memory: 1Gi

secret:
  name: color-server-secret